### ISSUE TITLE
Setting template_namespace not working

### ISSUE THREAD

**Issue by zacksiri** [leshill/hogan_assets#15]
Hi I am having issues setting the template_namespace via the initializer it doesn't seem to be working, it keeps falling back to HoganTemplates instead of the one I set.

**Comment by zacksiri** [comment]
ok nevermind, it seems i had to expire all my assets by changing:

application.rb

```
config.assets.version = '1.x' 
```

**Comment by zacksiri** [comment]
I am having issues with deployment to heroku and using this option, any thing i can do?

**Comment by leshill** [comment]
Hi @zacksiri,

Is `config.assets.initialize_on_precompile` set to false? If so, the initializers are not run when Heroku precompiles the assets.

**Comment by LucasCioffi** [comment]
Great gem!

@leshill I'm also running into an issue with Heroku precompiling (styles seem to not be available when I'm using Hogan Assets for Twitter's Typeahead as in the bottom example: http://twitter.github.io/typeahead.js/examples/ ).

Bottom line up front: 1) I'm writing this comment to understand where template's CSS comes from.  I think that it may be coming from Twitter bootstrap in my case; I just want to make sure that it's not coming from inside the gem somewhere-- I didn't see it in the gem's source code. 2) Is there a similar solution for this gem as there is for the Active Admin gem mentioned below?

As you mention above, the reason the styles are not present is likely that Heroku requires config.assets.initialize_on_precompile = false in application.rb.  Rails docs confirm this at http://guides.rubyonrails.org/asset_pipeline.html#precompiling-assets Side note: It seems this Heroku Labs project https://devcenter.heroku.com/articles/labs-user-env-compile makes it possible to set config.assets.initialize_on_precompile = true (but it didn't resolve the problem for me).

The folks working on the Active Admin gem seemed to have a workaround at https://github.com/gregbell/active_admin/wiki/Heroku-Cedar-deployment-with-the-Asset-Pipeline by adding config.assets.precompile += %w( active_admin.css active_admin.js active_admin/print.css ) to application.rb.  Are there CSS files in the Hogan Assets gem which would make a similar solution work for us?  To me, it looks like there aren't any CSS files in this gem.  So it's possible that I'm depending on the CSS files from Twitter Bootstrap.  I know that the CSS files are in my project, because when I change config.assets.compress = false in application.rb, the styles are present (but it causes another issue with JQuery and perhaps all assets to load twice, so it's not a workable solution).

So perhaps I need to precompile bootstrap in a similar way as the Active Admin solution: config.assets.precompile += %w( active_admin.css active_admin.js active_admin/print.css )

FWIW, I'm calling Hogan from a coffeescript file like this (note that it's not displaying perfectly in this comment):
$("#search_box").typeahead [
  name: "search-options"
  remote: "/typeahead/%QUERY.json"
  template: "<p><strong>{{value}}</strong></p>"
  engine: Hogan
]

Thanks for reading all that!!

**Comment by leshill** [comment]
Hi @LucasCioffi,

There is no CSS in the `hogan_assets` gem.

Yes, you need to have a way to include the CSS into the asset pipeline.

Usually this is done in your `application.css` using `require` — see section 2.4 of http://guides.rubyonrails.org/asset_pipeline.html — or via `import` if you are using Sass or Less.

As mentioned by the `active_admin` folks, you can add manifest files to the asset pipeline to pull the files in directly. Those files must then be linked via a `stylesheet_link_tag` in the page's HEAD (usually done in your layout(s)) — See section 2.3.

Hope that helps!
